import Foundation
#if os(Windows) || os(Linux)
import CSQLite
#else
import SQLite3
#endif
#if canImport(FoundationNetworking) && !os(Windows)
import FoundationNetworking
#endif

/// Reads Grok Bot's separate weekly allowance from Cursor's Sand dashboard service.
///
/// Grok Bot is metered on the signed-in Cursor account, so this deliberately reuses
/// Cursor's existing state database. It never opens or decrypts `Grok Bot Safe Storage`
/// and therefore cannot trigger a keychain authorization prompt.
final class GrokBotQuotaService: @unchecked Sendable {
    private static let source = "Cursor Grok Bot API"
    private static let endpoint =
        "https://api2.cursor.sh/aiserver.v1.DashboardService/GetSandUsageStatus"
    private static let SQLITE_TRANSIENT = unsafeBitCast(
        OpaquePointer(bitPattern: -1), to: sqlite3_destructor_type.self
    )

    private struct Credential {
        let token: String
        let userID: String
        let email: String?
        let machineID: String
        let membershipType: String?
    }

    private let fileManager: FileManager
    private let stateDatabasePath: String

    init(
        fileManager: FileManager = .default,
        stateDatabasePath: String = AppPaths.appSupport(
            "Cursor", "User", "globalStorage", "state.vscdb"
        )
    ) {
        self.fileManager = fileManager
        self.stateDatabasePath = stateDatabasePath
    }

    func fetch() -> ProviderQuotaSnapshot {
        guard UserDefaults.standard.bool(for: .cursorCloudFetchEnabled, default: true) else {
            return .unavailable("Cursor cloud access is disabled in Settings.", source: Self.source)
        }
        guard let credential = credentialFromCursorState() else {
            return .unavailable("Cursor login was not found.", source: Self.source)
        }
        guard let data = request(credential: credential) else {
            return .unavailable("Grok Bot quota request failed.", source: Self.source)
        }
        guard var snapshot = Self.decodeResponse(data) else {
            return .unavailable("Grok Bot quota response was not recognized.", source: Self.source)
        }
        snapshot.account = SubscriptionAccountIdentity(
            id: credential.userID,
            email: credential.email
        )
        if snapshot.planType == nil { snapshot.planType = credential.membershipType }
        return snapshot
    }

    static func decodeResponse(_ data: Data, now: Date = Date()) -> ProviderQuotaSnapshot? {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let usedPercent = number(root["usagePercent"]) else { return nil }
        let reset = date(root["nextResetTimestampUtc"])
        let start = date(root["currentPeriodStart"])
        let minutes = start.flatMap { start in
            reset.map { max(0, Int($0.timeIntervalSince(start) / 60)) }
        } ?? 10_080
        let bucket = CodexQuotaBucket(
            id: "grok-bot:weekly",
            name: "Grok Bot",
            usedPercent: min(100, max(0, usedPercent)),
            windowMinutes: minutes,
            resetsAt: reset
        )
        return ProviderQuotaSnapshot(
            status: .available,
            groups: [ProviderQuotaGroup(
                id: "grok-bot:plan", name: "Subscription", buckets: [bucket]
            )],
            planType: informativePlan(root["grokPlanLabel"] as? String),
            refreshedAt: now,
            source: source,
            message: nil
        )
    }

    /// Reproduces the checksum generated by Grok Bot's current Sand client.
    /// The prefix is time-bounded; the stable machine identifier is read from
    /// Cursor's ordinary state database rather than any protected keychain item.
    static func cursorChecksum(machineID: String, now: Date = Date()) -> String {
        let tick = UInt64(max(0, floor(now.timeIntervalSince1970 / 1_000)))
        var bytes = stride(from: 5, through: 0, by: -1).map {
            UInt8(truncatingIfNeeded: tick >> UInt64($0 * 8))
        }
        var seed: UInt8 = 165
        for index in bytes.indices {
            let transformed = UInt16(bytes[index] ^ seed) + UInt16(index)
            bytes[index] = UInt8(truncatingIfNeeded: transformed)
            seed = bytes[index]
        }
        let prefix = Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
        return prefix + machineID
    }

    private func credentialFromCursorState() -> Credential? {
        guard fileManager.fileExists(atPath: stateDatabasePath) else { return nil }
        var database: OpaquePointer?
        guard sqlite3_open_v2(stateDatabasePath, &database, SQLITE_OPEN_READONLY, nil) == SQLITE_OK else {
            return nil
        }
        defer { sqlite3_close(database) }
        guard let token = itemValue(database: database, key: "cursorAuth/accessToken"),
              let userID = CursorQuotaService.userID(from: token),
              let machineID = itemValue(database: database, key: "storage.serviceMachineId") else {
            return nil
        }
        return Credential(
            token: token,
            userID: userID,
            email: itemValue(database: database, key: "cursorAuth/cachedEmail"),
            machineID: machineID,
            membershipType: itemValue(database: database, key: "cursorAuth/stripeMembershipType")
        )
    }

    private func itemValue(database: OpaquePointer?, key: String) -> String? {
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(
            database,
            "SELECT value FROM ItemTable WHERE key=?1 LIMIT 1",
            -1,
            &statement,
            nil
        ) == SQLITE_OK else { return nil }
        defer { sqlite3_finalize(statement) }
        sqlite3_bind_text(statement, 1, key, -1, Self.SQLITE_TRANSIENT)
        guard sqlite3_step(statement) == SQLITE_ROW,
              let pointer = sqlite3_column_text(statement, 0) else { return nil }
        return Self.nonEmpty(
            String(cString: pointer).trimmingCharacters(in: .whitespacesAndNewlines)
        )
    }

    private func request(credential: Credential) -> Data? {
        for attempt in 0..<2 {
            if let data = requestOnce(credential: credential) { return data }
            if attempt == 0 { Thread.sleep(forTimeInterval: 0.25) }
        }
        return nil
    }

    private func requestOnce(credential: Credential) -> Data? {
        let headers = [
            "Accept": "application/json",
            "Authorization": "Bearer \(credential.token)",
            "Content-Type": "application/json",
            "x-cursor-checksum": Self.cursorChecksum(machineID: credential.machineID),
            "x-cursor-client-source": "sand-desktop",
            "x-cursor-client-type": "sand",
            "x-ghost-mode": "true",
            "x-sand-box-namespace": "prod",
        ]
        let body = Data("{}".utf8)
        #if os(Windows)
        guard let response = try? WindowsNativeHTTP.request(
            url: Self.endpoint,
            method: "POST",
            headers: headers,
            body: body,
            connectTimeout: 8,
            sendTimeout: 8,
            receiveTimeout: 15
        ), response.statusCode == 200 else { return nil }
        return response.body
        #else
        guard let endpoint = URL(string: Self.endpoint) else { return nil }
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.httpBody = body
        request.timeoutInterval = 15
        for (name, value) in headers { request.setValue(value, forHTTPHeaderField: name) }
        let semaphore = DispatchSemaphore(value: 0)
        let box = HTTPResultBox()
        URLSession.shared.dataTask(with: request) { data, response, _ in
            box.store(data: data, response: response)
            semaphore.signal()
        }.resume()
        guard semaphore.wait(timeout: .now() + 16) == .success,
              let response = box.load(), response.statusCode == 200 else { return nil }
        return response.data
        #endif
    }

    #if !os(Windows)
    private final class HTTPResultBox: @unchecked Sendable {
        private let lock = NSLock()
        private var result: (data: Data, statusCode: Int)?
        func store(data: Data?, response: URLResponse?) {
            guard let data, let response = response as? HTTPURLResponse else { return }
            lock.withLock { result = (data, response.statusCode) }
        }
        func load() -> (data: Data, statusCode: Int)? { lock.withLock { result } }
    }
    #endif

    private static func number(_ value: Any?) -> Double? {
        if let value = value as? NSNumber { return value.doubleValue }
        if let value = value as? String { return Double(value) }
        return nil
    }

    private static func date(_ value: Any?) -> Date? {
        if let value = value as? NSNumber {
            let seconds = value.doubleValue > 10_000_000_000
                ? value.doubleValue / 1_000 : value.doubleValue
            return Date(timeIntervalSince1970: seconds)
        }
        guard let value = value as? String else { return nil }
        if let milliseconds = Double(value), milliseconds > 10_000_000_000 {
            return Date(timeIntervalSince1970: milliseconds / 1_000)
        }
        let plain = ISO8601DateFormatter()
        if let parsed = plain.date(from: value) { return parsed }
        let fractional = ISO8601DateFormatter()
        fractional.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return fractional.date(from: value)
    }

    private static func nonEmpty(_ value: String?) -> String? {
        guard let value, !value.isEmpty else { return nil }
        return value
    }

    private static func informativePlan(_ value: String?) -> String? {
        guard let value = nonEmpty(value?.trimmingCharacters(in: .whitespacesAndNewlines)),
              value.caseInsensitiveCompare("Grok Bot Plan") != .orderedSame else { return nil }
        return value
    }
}
